version: '3.9'
services:
  postgres:
    container_name: invest-path-postgres
    image: postgres:16.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: InvestPath
    volumes:
      - ./pgdata:/var/lib/postgresql/data